name: Deploy Storybook to GitHub Pages

on:
  pull_request:
    types: [closed]
    branches:
      - "dev"  # dev 브랜치로 PR이 병합될 때 실행

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    # PR이 병합된 경우에만 실행
    if: github.event.pull_request.merged == true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/storybook/
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Install dependencies
      run: npm install
      
    - name: Build Storybook
      run: npm run build-storybook
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'storybook-static'
        name: storybook
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: storybook
        path: 'storybook' 